blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.PostDetailView.as_view(), name='post_detail'),
]

jobs/urls.py
from django.urls import path
import . views

app_name = 'jobs'

urlpatterns = [
    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', jobs.views.JobListView.as_view(), name='home'),
    path('create-job/', jobs.views.create_job, name='create_job'),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    image = models.ImageField(upload_to='images/posts/')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

jobs/models.py
from django.db import models

class Job(models.Model):
    image = models.ImageField(upload_to='images/jobs/')
    summary = models.CharField(max_length=200)

    def __str__(self):
        return self.summary[:130] + '...'

jobs/forms.py
from django import forms
from .models import Job

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ('image', 'summary')
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'summary': forms.TextInput(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from . models import Post
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView

class PostListView(ListView):
    queryset = Post.objects.filter(status='published')
    context_object_name = 'posts'
    template_name = 'blog/post/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'blog'
        return context

class PostDetailView(TemplateView):
    template_name = 'blog/post/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, publish__year=kwargs['year'], publish__month=kwargs['month'],
            status='published', publish__day=kwargs['day'], slug=kwargs['post'])
        context['page'] = 'blog'
        return context

# def index(request):
#     posts = Post.objects.filter(status='published')
#     page = 'blog'
#     return render(request, 'blog/post/index.html', {'posts':posts, 'page':page})

# def detail(request, year, month, day, post):
#     post = get_object_or_404(Post, publish__year=year, publish__month=month,
#         status='published', publish__day=day, slug=post )
#     return render(request, 'blog/post/detail.html', {'post':post})

jobs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from . models import Job
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .forms import JobForm

# def home(request):
#     jobs = Job.objects.all()
#     page = 'home'
#     return render(request, 'jobs/home.html', {'jobs':jobs, 'page':page})

class JobListView(ListView):
    model = Job
    context_object_name = 'jobs'
    template_name = 'jobs/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'home'
        return context

def create_job(request):
    if request.method == 'POST':
        # Add request.FILES in order to upload image to the model
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            job = form.save(commit=False)
            job.image = form.cleaned_data['image']
            job.summary = form.cleaned_data['summary']
            job.save()
    else:
        form = JobForm()
    return render(request, 'jobs/create.html', {'form':form})

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>GTJ</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">GTJ</a>
      <img src="{% static "japan1.png" %}" alt="" width="30px">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link {% if page == 'home' %} active {% endif %}" href="{% url 'home' %}">Home</a>
          <a class="nav-item nav-link {% if page == 'blog' %} active {% endif %}" href="{% url 'blog:post_list' %}">Blog</a>
        </div>
      </div>
    </nav>
  </header>

  <main role="main">

    {% block content %}
    {% endblock %}

  </main>

  <footer class="text-muted bg-dark">
    <div class="container text-center">
      &copy; Aleksandr {% now "Y" %}
    </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container mt-3">
  <h2 class="text-center">{{ post.title }}</h2>
  <p class="text-center">{{ post.publish | date:"d M Y"}}</p>
  <div class="row justify-content-center">
    <div style="width: 500px">
      <img src="{{ post.image.url }}" class="img-fluid" alt="">
    </div>
  </div>
  <br>
  {{ post.body | linebreaks }}
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="bg-light">
  <br>
  <div class="container">
  {% for post in posts%}

    <div class="row">
      <div class="col-md-4">
        <img src="{{ post.image.url }}" class="rounded img-fluid" alt="...">
      </div>
      <div class="col-md-8 pl-5">
        <h3 class="mb-0">
          <a href="{{ post.get_absolute_url }}"><h3>{{ post.title }}</h3></a>
        </h3>
        <div class="mb-1 text-muted">{{ post.publish | date:"d M Y"}}</div>
        <p class="card-text mb-auto">{{ post.body |truncatewords:30|linebreaks }}</p>
        <a href="{{ post.get_absolute_url }}">Подробнее</a>
      </div>
    </div>
    <br>

  {% endfor %}
  </div>
</div>

{% endblock %}

jobs/templates/jobs/create.html
{% extends 'blog/base.html' %}
{% block content %}
<div style="width:300px; margin-left:100px">
<form action="." class="form-group" method="post" enctype="multipart/form-data">
  {{ form }}
  {% csrf_token %}
  <p><input type="submit" value="Add job"></p>
</form>
</div>
{% endblock %}

jobs/templates/jobs/home.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Great Trip Japan</h1>
        <p class="lead text-muted">Даже путь в тысячу ри начинается с одного шага.</p>
        <img src="{% static 'rafiki.jpg' %}" alt="venom" width="300px">
        <p>
          <a href="mailto:mixft@mail.ru" class="btn btn-primary my-2">Отправить нам письмо</a>
        </p>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">

        <div class="row">
          {% for job in jobs %}
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top" src="{{ job.image.url }}" alt="Card image cap">
              <div class="card-body">
                <p class="card-text">{{ job.summary }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}